<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class terreno extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('terreno')->insert([
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
        
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'55000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            // Manzana 2
           //grandes 4
           [
            'id_manzana'=>'2',//1
            'superficie_terreno'=>'180',
            'precio'=>'45000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//2
            'superficie_terreno'=>'180',
            'precio'=>'45000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//3
            'superficie_terreno'=>'180',
            'precio'=>'45000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//4
            'superficie_terreno'=>'180',
            'precio'=>'45000',
            'estado_terreno'=>'libre'
        ],

       //mediano 8
        [
            'id_manzana'=>'2',//1
            'superficie_terreno'=>'150',
            'precio'=>'40000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//2
            'superficie_terreno'=>'150',
            'precio'=>'40000',
            'estado_terreno'=>'libre'
        ],

        [
            'id_manzana'=>'2',//3
            'superficie_terreno'=>'150',
            'precio'=>'40000',
            'estado_terreno'=>'libre'
        ],

        [
            'id_manzana'=>'2',//4
            'superficie_terreno'=>'150',
            'precio'=>'40000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//5
            'superficie_terreno'=>'150',
            'precio'=>'40000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//6
            'superficie_terreno'=>'150',
            'precio'=>'40000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//7
            'superficie_terreno'=>'150',
            'precio'=>'40000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//8
            'superficie_terreno'=>'150',
            'precio'=>'40000',
            'estado_terreno'=>'libre'
        ],
       //chicos 7
        [
            'id_manzana'=>'2',//1
            'superficie_terreno'=>'100',
            'precio'=>'35000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//2
            'superficie_terreno'=>'100',
            'precio'=>'35000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//3
            'superficie_terreno'=>'100',
            'precio'=>'35000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//4
            'superficie_terreno'=>'100',
            'precio'=>'35000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//5
            'superficie_terreno'=>'100',
            'precio'=>'35000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//6
            'superficie_terreno'=>'100',
            'precio'=>'35000',
            'estado_terreno'=>'libre'
        ],
        [
            'id_manzana'=>'2',//7
            'superficie_terreno'=>'100',
            'precio'=>'35000',
            'estado_terreno'=>'libre'
        ],




        ]);
        
    }
}
