<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class terreno extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('terreno')->insert([
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
        
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'55000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'100',
                'precio'=>'35000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'150',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],
            [
                'id_manzana'=>'1',		
                'superficie_terreno'=>'180',
                'precio'=>'40000',
                'estado_terreno'=>'libre'
            ],



        ]);
        
    }
}
